version: '3.9'
services:
  fuss-2-www:
    image: anssi/fcsc2020-web-fuss-2-www:latest
    ports:
      - "80:80"
    depends_on:
      - fuss-2-mongodb
    networks:
      - fuss-2-external
      - fuss-2-internal
      
  fuss-2-mongodb:
    image: mongo:4.2.6
    ports:
      - "27017:27017"
    hostname: "fuss-2-mongodb"
    networks:
      - fuss-2-internal
      
  fuss-2-bot:
    image: anssi/fcsc2020-web-fuss-2-bot:latest
    environment:
      - MONGO_DB=fcsc2020
      - MONGO_HOST=fuss-2-mongodb
      - CHALLENGE_URL=http://fuss-2-www/
      - ADMIN_TOKEN=uUmuSb8wINivIJVyn05v8ZQ9iMYa2BAQVA7ZXfc6IZ1PPIdz
      - BOT_TIMEOUT=10000 #in ms
    depends_on:
      - fuss-2-mongodb
      - fuss-2-www
    networks:
      - fuss-2-internal

networks:
  fuss-2-external:
  fuss-2-internal:
    internal: true
 